import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { IDENTITY_PATH, loadIdentity } from "../src/identity";

const out = fileURLToPath(new URL("../src/identity.generated.ts", import.meta.url));
const identity = loadIdentity(IDENTITY_PATH);
const body = [
  "// GENERATED by packages/config/scripts/gen-identity.ts from identity.yaml — do not edit; run `pnpm --filter @twin/config gen`.",
  'import type { Identity } from "./identity";',
  "",
  `export const identity: Identity = ${JSON.stringify(identity, null, 2)};`,
  "",
].join("\n");
writeFileSync(out, body);
console.log(`wrote ${out}`);
